CREATE DATABASE Atmos;

USE Atmos;

CREATE TABLE MeteoData (
fecha DATETIME NOT NULL,
temp INTEGER NOT NULL DEFAULT 0,
hum INTEGER NOT NULL DEFAULT 0,
luz INTEGER NOT NULL DEFAULT 0,
pres INTEGER NOT NULL DEFAULT 0
);

